Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "categories/index"
  get "categories/new"
  get "categories/edit"
  get "pages/about"
  get "pages/contact"
  # Devise user authentication
  devise_for :users

  # Homepage
  root "home#index"

  # Products (browse + admin CRUD)
  resources :products
  resources :categories, except: [:show]


  # Cart (each user has one)
  resource :cart, only: [:show]
  resources :orders, only: [:new, :create, :show]


  # Cart items: add, update, remove
  resources :cart_items, only: [:create, :update, :destroy]

  # Optional: remove autogenerated cart_items/home routes
  # get "cart_items/create"
  # get "cart_items/update"
  # get "cart_items/destroy"
  # get "cart/show"
  # get "home/index"

  # Health check & PWA (keep if needed)
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "/about", to: "pages#about"
  get "/contact", to: "pages#contact"
  get "/pages/:slug/edit", to: "pages#edit", as: :edit_page
  patch "/pages/:slug", to: "pages#update", as: :page
  get "categories/:id/products", to: "categories#products", as: :category_products
  get "checkout", to: "orders#new", as: :checkout

end
